POST http://localhost:3000/api/vnpay/create_payment_url
Content-Type: application/json

{
  "amount": 3000000,
  "orderId": 5,
  "orderInfo": "Thanh toán đơn hàng #5"
}

POST http://localhost:3000/api/auth/login
Content-Type: application/json
{
  "email": "lethikimoanh2k4@gmail.com",
  "password": "1234567"
}
